// export { default as banner1 } from "../../assets/banner-01.jpg";
// export { default as banner2 } from "../../assets/banner-02.jpg";
// export { default as banner3 } from "../../assets/banner-03.jpg";
// export { default as blogBanner } from "/assets/blog-trending.jpg";
// export { default as instaPost01 } from "../../assets/insta-post-01.jpg";
// export { default as instaPost02 } from "../../assets/insta-post-02.jpg";
// export { default as instaPost03 } from "../../assets/insta-post-03.jpg";
// export { default as instaPost04 } from "../../assets/insta-post-04.jpg";
// export { default as instaPost05 } from "../../assets/insta-post-05.jpg";
// export { default as instaPost06 } from "../../assets/insta-post-06.jpg";
// export { default as instaPost07 } from "../../assets/insta-post-07.jpg";
// export { default as instaPost08 } from "../../assets/insta-post-08.jpg";
// export { default as logoDark } from "/assets/logo-dark.png";
// export { default as logoLight } from "/assets/logo-light.png";
// export { default as post01 } from "../../assets/post-01.jpg";
// export { default as post02 } from "../../assets/post-02.jpg";
// export { default as post03 } from "../../assets/post-03.jpg";
// export { default as post04 } from "../../assets/post-04.jpg";
// export { default as post05 } from "../../assets/post-05.jpg";
// export { default as post06 } from "../../assets/post-06.jpg";
// export { default as post07 } from "../../assets/post-07.jpg";
// export { default as post08 } from "../../assets/post-08.jpg";
// export { default as post09 } from "../../assets/post-09.jpg";
// export { default as post10 } from "../../assets/post-10.jpg";
// export { default as post11 } from "../../assets/post-11.jpg";
// export { default as post12 } from "../../assets/post-12.jpg";
// export { default as user } from "/assets/user.png";

export { default as AssistantItem } from "../features/AssistantItem";
export { default as BlogItem } from "../features/BlogItem";
export { default as BlogPageItem } from "../features/BlogPageItem";
export { default as Button } from "../features/Button";
export { default as Navbar } from "../features/Navbar";
export { default as ScrollTop } from "../features/ScrollTop";
export { default as SearchBar } from "../features/SearchBar";
export { default as SectionHeading } from "../features/SectionHeading";
export { default as SocialIcons } from "../features/SocialIcons";
export { default as Topbar } from "../features/Topbar";

export { default as AboutMe } from "../sections/AboutMe.tsx";
export { default as Banner } from "../sections/Banner";
export { default as BannerQuote } from "../sections/BannerQuote";
export { default as BlogAside } from "../sections/BlogAside";
export { default as BlogMain } from "../sections/BlogMain";
export { default as Footer } from "../sections/Footer";
export { default as Header } from "../sections/Header";
export { default as InstaPosts } from "../sections/InstaPosts";
export { default as LatestPosts } from "../sections/LatestPosts";
export { default as MyAssistants } from "../sections/MyAssistants";
export { default as Newsletter } from "../sections/Newsletter";
export { default as PageBanner } from "../sections/PageBanner";
export { default as PopularPosts } from "../sections/PopularPosts";

// export { default as About } from "../pages/About";
// export { default as BlogDetail } from "../pages/BlogDetail";
// export { default as BlogsPage } from "../pages/BlogsPage";
// export { default as ContactUs } from "../pages/ContactUs";
// export { default as Home } from "../pages/Home";
// export { default as Login } from "../pages/Login";
// export { default as Page404 } from "../pages/Page404";
// export { default as Register } from "../pages/Register";
